name: Vérification du respect des spécifications

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Installation Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Vérification du schéma et des fichiers d'exemples
      run: |
        frictionless validate --type schema schema.json
        frictionless validate --schema schema.json exemple-valide.csv
